### PR TITLE
return last_message of conversations if this field is requested

### PR DESCRIPTION
**Pull request by datbth**

### CODE REVIEW

**Comment by daohoangson** [comment]
Please do the same for `first_message` for consistency. We should stop using `XenForo_Model_Conversation::FETCH_FIRST_MESSAGE`.

**Review by daohoangson — DISMISSED** [review]
Please do the same for first_message for consistency. We should stop using `XenForo_Model_Conversation::FETCH_FIRST_MESSAGE`.

**Comment by datbth** [comment]
I've made my adjustments, pls check again

**Comment by daohoangson** [comment]
I'm making some changes to this branch (you **DON'T** need to update the PR):

- Update actionSingle to use _prepareConversations
- Do not use array short syntax, some XenForo instances are still running PHP 5.3.
- Use `bdApi_getConversationMessagesByIds` instead of `getConversationMessagesByIds` to avoid conflicts. I have also reimplemented the method (see 59ac93f)
- Do not _filterDataSingle within preparation, do use _filterDataMany in the action routine instead.
- Update document

**Pull request merged**
