### PR TITLE
Fixed length of varchar indexes

### PR DESCRIPTION
**Pull request by scrummer**
When indexing VARCHARs there is a maximum length of 190 chars. Otherwise there occures an exception.

### CODE REVIEW

**Comment by daohoangson** [comment]
Interesting, apparently the limit is lower with utf8mb4 charset. Anyway, the document stated that 191 is the limit? https://dev.mysql.com/doc/refman/8.0/en/innodb-restrictions.html

**Comment by scrummer** [comment]
Ay, yes... I've used 190 here because I did the same in one of our/mine projects (e.g. https://github.com/dachcom-digital/pimcore-news/commit/78d72bb2051f868dae6035ffca90a28949e5603c#diff-fd9f0c28a0375b5f55b06b521c26a05aL220 )

It should be possible to change it to 191 without problems but 190 is a much nicer integer ;)

**Comment by daohoangson** [comment]
Understood.

**Comment by daohoangson** [comment]
The schema will now switch to use varbinary for better performance, see bdb6d37. I'm closing this PR now.

**Pull request closed without merging**
